### ISSUE TITLE
Make it stop!

### ISSUE THREAD

**Issue by ornato-t** [benzara-tahar/svelte-animated-counter#2]
Hi! I really like this tool you built and I'm trying to integrate it with a website I'm working on.  
I've noticed that, if I set `loop={true}`, instead of stopping at the last (or first) element of the `values` array, the count goes on for one more step, leaving a blank space instead of a number.

This happened with both the `up` and `down` directions. Is this intended or a bug? And if it is intended, can you suggest other ways to make the counter stick to its final value once it ends?

**Comment by benzara-tahar** [comment]
Appreciate your feedback, I will check that tomorrow 
Edit: just saw your PR, will test and merge if it goes well tomorrow as well

**Comment by ornato-t** [comment]
Gotcha, thank you for the quick answer.

**Comment by benzara-tahar** [comment]
just release v 0.0.3 on npm, should  be all good now

**Comment by ornato-t** [comment]
Worked like a charm, thank you!
